LIBS += $(LIB)

OBJS := \
  $(DIR)abbr1s1.o \
  $(DIR)abbr1s2.o \
  $(DIR)abbr1s3.o \
  $(DIR)abbr1s4.o \
  $(DIR)abbr1s5.o \
  $(DIR)triangle_I2G4_I2G5_I2G6.o \
  $(DIR)triangle_I2G4_I2G5.o \
  $(DIR)triangle_I2G4.o \
  $(DIR)triangle_I3G4_I3G5_I3G6_Ind1_Ind2_Ind3_Ind4_Ind5_Ind6.o \
  $(DIR)triangle_I3G4_I3G5_I3G6.o \
  $(DIR)triangle_I3G4_I3G5.o \
  $(DIR)triangle_I3G4.o \
  $(DIR)triangle_I9G4_I9G5_I9G6.o \
  $(DIR)triangle.o \
  $(DIR)SquaredME.o

$(LIB): $(LIB)($(OBJS))

$(LIB)($(OBJS)): F-squaredme.d $(DIR)vars.h

